name: Build Example Resume

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
          pip install -r requirements.txt

      - name: Build example resume
        run: |
          bash make_resume.sh examples/example_resume.md

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: example-resume
          path: output/