name: Build Example Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache TeX Live
        id: cache-texlive
        uses: actions/cache@v4
        with:
          path: /usr/local/texlive
          key: ${{ runner.os }}-texlive-v1
          restore-keys: |
            ${{ runner.os }}-texlive-

      - name: Install dependencies
        run: |
          sudo apt-get update
          if [ ! -d "/usr/local/texlive" ]; then
            sudo apt-get install -y pandoc texlive-xetex texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
          fi
          sudo apt-get install -y fonts-inter || true

      - name: Build Example Resume
        run: bash make_demo.sh

      - name: Upload generated files
        uses: actions/upload-artifact@v4
        with:
          name: mkresume-example
          path: output/